// export const ADD_RESOURCE = 'ADD_RESOURCE';
// export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
// export const ADD_RESOURCE_ERROR = 'ADD_RESOURCE_ERROR';

// export const GET_PRIVATE_ARTICLES = 'GET_PRIVATE_ARTICLES';
// export const GET_PRIVATE_ARTICLES_SUCCESS = 'GET_PRIVATE_ARTICLES_SUCCESS';
// export const GET_PRIVATE_ARTICLES_ERROR = 'GET_PRIVATE_ARTICLES_ERROR';

// export const GET_PRIVATE_VIDEOS = 'GET_PRIVATE_VIDEOS';
// export const GET_PRIVATE_VIDEOS_SUCCESS = 'GET_PRIVATE_VIDEOS_SUCCESS';
// export const GET_PRIVATE_VIDEOS_ERROR = 'GET_PRIVATE_VIDEOS_ERROR';

// export const SEARCH_RESOURCE = 'SEARCH_RESOURCE';
// export const SEARCH_RESOURCE_SUCCESS = 'SEARCH_RESOURCE_SUCCESS';
// export const SEARCH_RESOURCE_ERROR = 'SEARCH_RESOURCE_ERROR';

export const MAKE_RESOURCE_PUBLIC_OR_PRIVATE = 'MAKE_RESOURCE_PUBLIC_OR_PRIVATE';
export const MAKE_RESOURCE_PUBLIC_OR_PRIVATE_SUCCESS = 'MAKE_RESOURCE_PUBLIC_OR_PRIVATE_SUCCESS';
export const MAKE_RESOURCE_PUBLIC_OR_PRIVATE_ERROR = 'MAKE_RESOURCE_PUBLIC_OR_PRIVATE_ERROR';

export const USER_DETAIL = 'USER_DETAIL';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_ERROR = 'USER_DETAIL_ERROR';

