export const ADD_RESOURCE = 'ADD_RESOURCE';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_ERROR = 'ADD_RESOURCE_ERROR';

export const GET_RESOURCE = 'GET_RESOURCE';
export const GET_RESOURCE_SUCCESS = 'GET_RESOURCE_SUCCESS';
export const GET_RESOURCE_ERROR = 'GET_RESOURCE_ERROR';
